version: "3"
services:
  express-template:
    build:
      context: ../express-template
    command: npm run dev
    volumes:
      - ../express-template/src:/usr/src/app/src
      # consider the following (though, it severely slows down hot deploy)
      # - ../express-template:/usr/src/app
  reservation-frontend:
    environment:
      - API_HOST=http://localhost:3000
